### ISSUE TITLE
all and upcoming appointment tab having same data

### ISSUE THREAD

**Issue by MaroofTech** [MaroofTech/vlcc-web-issue-tracker#71]

**Comment by kanishkavayuz** [comment]
@MaroofTech  this has been resolved

**Comment by MaroofTech** [comment]
@kanishkavayuz not resolved video appointment tab pleas check snippet
![Screenshot from 2021-12-02 16-46-44](https://user-images.githubusercontent.com/78342064/144412155-a9efd232-bad0-49cb-89de-ef30f37a195e.png)
.
![Screenshot from 2021-12-02 16-46-50](https://user-images.githubusercontent.com/78342064/144412121-758bafad-6c28-4d05-b557-4f9b743c4f03.png)
